### ISSUE TITLE
Width set to 50%

### ISSUE THREAD

**Issue by miliakhaled** [Vin-it/react-sort-list#18]
Hello, thank you very much for the simple and great component,
I wonder why you set the width of "dropBox" class to 50%,
i was trying to changed it, but it seems you defined it as line style

**Comment by Vin-it** [comment]
Hi @miliakhaled, Thank you :) 

Sorry for not getting back to you earlier. This was the hobby project I built as a beginner and got deprioritized. 

Regarding the width -that's a good point, I should probably remove that line. 

Meanwhile, feel free to fork it and modify the repo :)
